{% set name = "photutils" %}
{% set version = "0.7.2" %}
{% set hash_value = "1305bc4b6bc8a22bfbd14c76a286a5c6e64d1921a99dec7d7036afc93cb8effe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  # Note: pip-based install fails due to wanting to download astropy-helpers
  script: python setup.py install --offline --single-version-externally-managed --record=files.txt
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - setuptools
  run:
    - python
    - astropy >=3.2
    - gwcs >=0.11
    - matplotlib-base >=2.2
    - numpy >=1.13
    - scikit-image >=0.14.2
    - scikit-learn
    - scipy

test:
  requires:
    - pytest-astropy
  imports:
    - photutils
    - photutils.aperture
    - photutils.background
    - photutils.centroids
    - photutils.datasets
    - photutils.detection
    - photutils.extern
    - photutils.geometry
    - photutils.isophote
    - photutils.morphology
    - photutils.psf
    - photutils.psf.matching
    - photutils.segmentation
    - photutils.utils

about:
  home: https://photutils.readthedocs.io/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: An Astropy package for photometry
  description: |
    Photutils is an Astropy package for detection and photometry of
    astronomical sources.
  doc_url: https://photutils.readthedocs.io/
  dev_url: https://github.com/astropy/photutils
